### ISSUE TITLE
Determine feasibility of store-bought inductors to detect small needles

### ISSUE THREAD

**Issue by timhoer** [Duke-BME-Design/needlelocalizer#2]

**Comment by mlp6** [comment]
Detail of why this is blocked?

**Comment by mlp6** [comment]
Also not associated with an MVP.

**Comment by gauriprasad** [comment]
Inductor does not seem to provide enough range to be feasibly used to detect needles.

**Comment by timhoer** [comment]
Waiting to purchase more inductors without size limit
